#!/usr/bin/env node

/**
 * Build the `ssr-edge` flavor of @uniweb/runtime — the worker-runtime.js SSR
 * isolate bundle plus its three globalThis-bridge shims — into dist/.
 *
 * OPT-IN, and deliberately so. This is NOT part of `pnpm build` and is NOT
 * shipped in the npm tarball: package.json `files` is ["src","dist"], and this
 * script lives at the repo root (unpublished). The published @uniweb/runtime
 * carries the `spa` (dist/app/**) and `ssr-node` (dist/ssr.js) flavors only; the
 * isolate target is produced on demand for whoever serves it. Keeping it opt-in
 * keeps the default build and the tarball lean while still giving a one-command
 * path to the artifact (so an SSR host or the `uniweb runtime register` CLI can
 * provision it without a bespoke build).
 *
 * Run it: `pnpm build:worker` (after `pnpm build:ssr`, which emits dist/ssr.js).
 *
 * Produces (consumed by a serverless JS isolate that has no package resolution
 * and must run a single React instance — an SSR/edge worker):
 *   dist/worker-runtime.js         React + jsx-runtime + @uniweb/core +
 *                                  react-dom/server + the SSR pipeline ALL
 *                                  inlined; writes its instances onto
 *                                  globalThis.__PLATFORM_* at module-eval time.
 *   dist/shims/react.js            modules-map shim re-exporting React's surface
 *                                  from globalThis.__PLATFORM_REACT.
 *   dist/shims/react-jsx-runtime.js   same idea for react/jsx-runtime.
 *   dist/shims/uniweb-core.js      same idea for @uniweb/core.
 *
 * This is a build-LINKAGE choice for the isolate environment (everything inlined,
 * one React), the peer of ssr-node's externalized linkage — not deployment code:
 * there are no host / CDN / account references here; uploading and serving the
 * artifact is a separate concern owned by whoever hosts it.
 */

import { existsSync, mkdirSync, writeFileSync, statSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Bundle dist/ssr.js into the ssr-edge artifact set.
 *
 * Why globalThis instead of inter-module imports? The isolate's module loader
 * resolves bare specifiers RELATIVE TO THE IMPORTING MODULE'S PACKAGE CONTEXT —
 * from inside the `react/jsx-runtime` shim, `import 'worker-runtime'` would be
 * looked up as `react/worker-runtime`. globalThis sidesteps that entirely.
 *
 * Why inline React (not externalize)? `react-dom/server` is CJS and internally
 * does `require('react')`. With React externalized via the modules map, esbuild
 * emits a runtime "Dynamic require not supported" error. React must live in one
 * self-contained bundle (worker-runtime.js) alongside react-dom/server.
 *
 * @param {string} runtimeDir - the @uniweb/runtime package dir (has dist/ssr.js).
 * @returns {Promise<{ workerRuntime: string, shims: Record<string, string> }>}
 *   workerRuntime = absolute path to dist/worker-runtime.js; shims keyed by their
 *   dist-relative path (`shims/react.js`, …) → the generated code.
 */
export async function buildWorkerRuntime(runtimeDir) {
  const { build: esbuild, stop: esbuildStop } = await import('esbuild')

  const ssrEntry = join(runtimeDir, 'dist', 'ssr.js')
  if (!existsSync(ssrEntry)) {
    throw new Error('dist/ssr.js not found — run `pnpm build:ssr` first')
  }

  // Resolve React/ReactDOM/core to absolute paths so esbuild's prefix-match
  // externalization doesn't stumble over `react-dom/server.browser`.
  const runtimeRequire = createRequire(join(runtimeDir, 'package.json'))
  const reactDir = dirname(runtimeRequire.resolve('react/package.json'))
  const reactDomDir = dirname(runtimeRequire.resolve('react-dom/package.json'))
  const reactDomServerBrowser = join(reactDomDir, 'server.browser.js')

  const alias = {
    react: reactDir,
    'react-dom': reactDomDir,
    'react-dom/server': reactDomServerBrowser,
  }

  // Walk node_modules upward from runtimeDir for esbuild's nodePaths.
  const nodePaths = []
  let dir = runtimeDir
  for (let i = 0; i < 10; i++) {
    const candidate = join(dir, 'node_modules')
    if (existsSync(candidate)) nodePaths.push(candidate)
    const parent = dirname(dir)
    if (parent === dir) break
    dir = parent
  }

  const distDir = join(runtimeDir, 'dist')
  const shimsDir = join(distDir, 'shims')
  if (!existsSync(shimsDir)) mkdirSync(shimsDir, { recursive: true })

  // Wrapper entry: set the globalThis bridges, then re-export the SSR pipeline.
  // esbuild bundles this with everything inlined (external: []).
  const wrapperPath = join(distDir, 'worker-runtime-entry.js')
  writeFileSync(
    wrapperPath,
    [
      '// AUTO-GENERATED by build-worker.js — do not edit',
      "import * as __PlatformReact from 'react'",
      "import * as __PlatformJsxRuntime from 'react/jsx-runtime'",
      "import * as __PlatformUniwebCore from '@uniweb/core'",
      'globalThis.__PLATFORM_REACT = __PlatformReact',
      'globalThis.__PLATFORM_JSX_RUNTIME = __PlatformJsxRuntime',
      'globalThis.__PLATFORM_UNIWEB_CORE = __PlatformUniwebCore',
      "export * from './ssr.js'",
      '',
    ].join('\n')
  )

  const outfile = join(distDir, 'worker-runtime.js')
  await esbuild({
    entryPoints: [wrapperPath],
    bundle: true,
    format: 'esm',
    platform: 'browser',
    external: [],
    outfile,
    minify: false,
    nodePaths,
    alias,
    conditions: ['browser', 'module'],
    logLevel: 'warning',
  })
  try {
    await esbuildStop?.()
  } catch {
    // esbuild's service teardown is best-effort
  }

  // Enumerate each package's real export names so the shims re-export each name
  // explicitly. Static `export *` doesn't propagate names from CJS-interop'd
  // packages reliably, so we list them — and the list stays in sync with whatever
  // React / @uniweb/core version is shipped.
  async function namesOf(spec) {
    const m = await import(runtimeRequire.resolve(spec))
    return Object.keys(m).filter((k) => k !== 'module.exports')
  }
  const reactNames = await namesOf('react')
  const jsxRuntimeNames = await namesOf('react/jsx-runtime')
  const uniwebCoreNames = await namesOf('@uniweb/core')

  function shim(globalThisKey, names) {
    return [
      `// AUTO-GENERATED — modules-map shim re-exporting from globalThis.${globalThisKey}.`,
      '// worker-runtime.js sets the bridge at module-eval time.',
      `const __ns = globalThis.${globalThisKey}`,
      'export default __ns?.default ?? __ns',
      ...names.filter((n) => n !== 'default').map((n) => `export const ${n} = __ns.${n}`),
      '',
    ].join('\n')
  }

  const shimsByPath = {
    'shims/react.js': shim('__PLATFORM_REACT', reactNames),
    'shims/react-jsx-runtime.js': shim('__PLATFORM_JSX_RUNTIME', jsxRuntimeNames),
    'shims/uniweb-core.js': shim('__PLATFORM_UNIWEB_CORE', uniwebCoreNames),
  }
  for (const [rel, code] of Object.entries(shimsByPath)) {
    writeFileSync(join(distDir, rel), code)
  }

  return { workerRuntime: outfile, shims: shimsByPath }
}

// CLI entry — the `build:worker` package script. Builds into this package's dist/.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const runtimeDir = dirname(fileURLToPath(import.meta.url))
  const kb = (p) => (statSync(p).size / 1024).toFixed(1)
  buildWorkerRuntime(runtimeDir)
    .then(({ workerRuntime, shims }) => {
      console.log(`✓ dist/worker-runtime.js (${kb(workerRuntime)} KB)`)
      for (const rel of Object.keys(shims)) {
        console.log(`✓ dist/${rel} (${kb(join(runtimeDir, 'dist', rel))} KB)`)
      }
    })
    .catch((err) => {
      console.error(`✗ build:worker failed: ${err.message}`)
      process.exit(1)
    })
}
